# Staging environment
name = "turno-pvu-backend-staging"
main = "worker.js"
compatibility_date = "2024-01-29"

[vars]
ENVIRONMENT = "staging"

[[d1_databases]]
binding = "TURNO_PVU_DB"
database_name = "turno-pvu-db-staging"
database_id = "9299c5ac-6f7a-4cee-964c-078ee4270425"

[[kv_namespaces]]
binding = "TURNO_PVU_CACHE"
id = ""

[observability]
enabled = true
